---
title: "Helmet EDA"
format: html
editor: visual
---

## Load in libraries and clean_helmet, modify data  

```{r}
library(dplyr)
library(ggplot2)

helmet <- read.csv("clean_helmet.csv") |> mutate_at(c('porosity','chemIndex'), as.factor) |>
  select(!chemistry) |> 
  filter(cycleNum <= 10000)
helmet <- na.omit(helmet)
```

## What does porosity do? Do more dense materials appear to last longer? Is there no effect?
```{r}
ggplot(helmet) + geom_point(aes(x=cycleNum,y=stiffness,color=porosity))
ggplot(helmet) + geom_point(aes(x=cycleNum,y=damping,color=porosity))

# separate by porosity maybe and then plot by each sample id
p71 <- helmet|> filter(porosity==71)
p81 <- helmet |> filter(porosity==81)

ggplot(p71,aes(x=cycleNum,y=stiffness,color=as.factor(sampleNum)))+geom_line()+geom_point()
ggplot(p71,aes(x=cycleNum,y=damping,color=as.factor(sampleNum)))+geom_line()+geom_point()

ggplot(p81,aes(x=cycleNum,y=stiffness,color=as.factor(sampleNum)))+geom_line()+geom_point()
ggplot(p81,aes(x=cycleNum,y=damping,color=as.factor(sampleNum)))+geom_line()+geom_point()
```

## What about the same thing but for chemical index?
```{r}
ggplot(helmet) + geom_point(aes(x=cycleNum,y=stiffness,color=chemIndex))
ggplot(helmet) + geom_point(aes(x=cycleNum,y=damping,color=chemIndex))

# separate by chemindex and then plot by each sample id
c79 <- helmet|> filter(chemIndex==79)
c100 <- helmet |> filter(chemIndex==100)
c121 <- helmet |> filter(chemIndex==121)

ggplot(c79,aes(x=cycleNum,y=stiffness,color=as.factor(sampleNum)))+geom_line()+geom_point()
ggplot(c79,aes(x=cycleNum,y=damping,color=as.factor(sampleNum)))+geom_line()+geom_point()

ggplot(c100,aes(x=cycleNum,y=stiffness,color=as.factor(sampleNum)))+geom_line()+geom_point()
ggplot(c100,aes(x=cycleNum,y=damping,color=as.factor(sampleNum)))+geom_line()+geom_point()

ggplot(c121,aes(x=cycleNum,y=stiffness,color=as.factor(sampleNum)))+geom_line()+geom_point()
ggplot(c121,aes(x=cycleNum,y=damping,color=as.factor(sampleNum)))+geom_line()+geom_point()
```

## Strain Rate vs freq and amplitude?
```{r}
ggplot(helmet, aes(x=strainRate,y=stiffness)) + geom_point()
ggplot(helmet, aes(x=strainRate,y=damping)) + geom_point()

ggplot(helmet, aes(x=freq,y=stiffness)) + geom_point()
ggplot(helmet, aes(x=freq,y=damping)) + geom_point()

ggplot(helmet, aes(x=amp,y=stiffness)) + geom_point()
ggplot(helmet, aes(x=amp,y=damping)) + geom_point()

```

## boxplot time
```{r}
ggplot(helmet) + geom_boxplot(aes(x=porosity,y=stiffness))
ggplot(helmet) + geom_boxplot(aes(x=porosity,y=damping))

ggplot(helmet) + geom_boxplot(aes(x=chemIndex,y=stiffness))
ggplot(helmet) + geom_boxplot(aes(x=chemIndex,y=damping))

ggplot(helmet) + geom_boxplot(aes(x=as.factor(cycleNum),y=stiffness))
ggplot(helmet) + geom_boxplot(aes(x=as.factor(cycleNum),y=damping))

ggplot(helmet) + geom_boxplot(aes(x=as.factor(sampleNum),y=stiffness))
ggplot(helmet) + geom_boxplot(aes(x=as.factor(sampleNum),y=damping))

```

## stressKpa and strain
```{r}
ggplot(helmet)+geom_point(aes(x=stresskpa,y=stiffness,color=(as.factor(sampleNum))))
ggplot(helmet)+geom_point(aes(x=stresskpa,y=damping,color=(as.factor(sampleNum))))

ggplot(helmet)+geom_point(aes(x=strain,y=stiffness,color=(as.factor(sampleNum))))
ggplot(helmet)+geom_point(aes(x=strain,y=damping,color=(as.factor(sampleNum))))

```

## Counts
```{r}
ggplot(helmet) + geom_count(aes(x=chemIndex,y=porosity))
```

