---
title: "Helmet EDA 2"
author: "Armelle Duston"
date: "2024-04-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
library(ggplot2)
library(tidyr)
library(GGally)
library(gplots)
library(gridExtra)
```

Import Data
```{r}
data <- read.csv("clean_helmet.csv")
#data <- subset(data, select = -c(chemistry))

data$chemIndex <- as.character(data$chemIndex)
data$porosity <- as.character(data$porosity)
data$sampleNum <- as.character(data$sampleNum)

data <- subset(data, cycleNum <= 10000)
data <- na.omit(data)

data <- subset(data, cycleNum != 0)
```


# Stiffness Frac EDA
```{r}

plot1 <- data |>
  subset(porosity == '71' & chemIndex == '79') |>
  ggplot(aes(x=log(cycleNum), y = stiffFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE) + 
  ggtitle("Porosity 71, Chem 79") + 
  theme(legend.position = "none",
        axis.title.x=element_blank()) 

plot2 <- data |>
  subset(porosity == '81' & chemIndex == '79') |>
  ggplot(aes(x=log(cycleNum), y = stiffFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE)  + 
  ggtitle("Porosity 81, Chem 79") + 
  theme(legend.position = "none")

plot3 <- data |>
  subset(porosity == '71' & chemIndex == '100') |>
  ggplot(aes(x=log(cycleNum), y = stiffFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE)  + 
  ggtitle("Porosity 71, Chem 100") +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.title.y=element_blank())

plot4 <- data |>
  subset(porosity == '81' & chemIndex == '100') |>
  ggplot(aes(x=log(cycleNum), y = stiffFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE)  + 
  ggtitle("Porosity 81, Chem 100") +
  theme(legend.position = "none",
        axis.title.y=element_blank())

plot5 <- data |>
  subset(porosity == '71' & chemIndex == '121') |>
  ggplot(aes(x=log(cycleNum), y = stiffFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE)  + 
  ggtitle("Porosity 71, Chem 121") +
  theme(legend.position = "none",
        axis.title.y=element_blank(),
        axis.title.x=element_blank())

plot6 <- data |>
  subset(porosity == '81' & chemIndex == '121') |>
  ggplot(aes(x=log(cycleNum), y = stiffFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE)  + 
  ggtitle("Porosity 81, Chem 121") +
  theme(legend.position = "none",
        axis.title.y=element_blank())

grid.arrange(plot1, plot3, plot5, plot2, plot4, plot6, nrow = 2, ncol = 3)

```


# Damping Frac EDA
```{r}

plot1 <- data |>
  subset(porosity == '71' & chemIndex == '79') |>
  ggplot(aes(x=log(cycleNum), y = dampFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE) + 
  ggtitle("Porosity 71, Chem 79") + 
  theme(legend.position = "none",
        axis.title.x=element_blank()) 

plot2 <- data |>
  subset(porosity == '81' & chemIndex == '79') |>
  ggplot(aes(x=log(cycleNum), y = dampFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE)  + 
  ggtitle("Porosity 81, Chem 79") + 
  theme(legend.position = "none")

plot3 <- data |>
  subset(porosity == '71' & chemIndex == '100') |>
  ggplot(aes(x=log(cycleNum), y = dampFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE)  + 
  ggtitle("Porosity 71, Chem 100") +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.title.y=element_blank())

plot4 <- data |>
  subset(porosity == '81' & chemIndex == '100') |>
  ggplot(aes(x=log(cycleNum), y = dampFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE)  + 
  ggtitle("Porosity 81, Chem 100") +
  theme(legend.position = "none",
        axis.title.y=element_blank())

plot5 <- data |>
  subset(porosity == '71' & chemIndex == '121') |>
  ggplot(aes(x=log(cycleNum), y = dampFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE)  + 
  ggtitle("Porosity 71, Chem 121") +
  theme(legend.position = "none",
        axis.title.y=element_blank(),
        axis.title.x=element_blank())

plot6 <- data |>
  subset(porosity == '81' & chemIndex == '121') |>
  ggplot(aes(x=log(cycleNum), y = dampFrac, col = sampleNum)) +
  geom_point() +
  geom_smooth(se = FALSE)  + 
  ggtitle("Porosity 81, Chem 121") +
  theme(legend.position = "none",
        axis.title.y=element_blank())

grid.arrange(plot1, plot3, plot5, plot2, plot4, plot6, nrow = 2, ncol = 3)

```


