---
title: "Helmet_wrangling"
author: "Armelle Duston"
date: "2024-02-27"
output: html_document
---

#hello 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries & read in 
```{r}
library(readxl)
library(plyr)
library(dplyr)
library(tidyr)
library(stringr)

Data <- read_excel("DMA_Fatigue_Data_from_Team_Wendy_Polyurethane_LLNL-MI-860456.xlsx", skip=3)
Data <- subset(Data, select = -c(62:64))

Data <- Data |>
  dplyr::rename(NVP_Cyc_N = NVP_Cyc_N...61,
         NVP_Cyc_M = NVP_Cyc_M...60,
         NVP_Cyc_L = NVP_Cyc_L...59)
```

# Extract info from sample_code
```{r}
extract_name_df <- Data |> 
  separate(col = SampleCode,
           into = c("chemistry", "chemIndex", "porosity", "sampleNum"))

```

# Pivot longer
```{r}
#split up into 4 df's and pivot longer on each subset
cyclesDf <- subset(extract_name_df, select = c(1:8,9:22))
stiffnessDf <- subset(extract_name_df, select = c(1:8,23:36))

cycle1 <- stiffnessDf$E1_MPA_Cyc_A

stiffF <- stiffnessDf[9:22]/cycle1

stiffnessDf2 <- stiffnessDf
stiffnessDf2[9:22] <- stiffF


dampingDf <- subset(extract_name_df, select = c(1:8,37:50))
nonlinearDf <- subset(extract_name_df, select = c(1:8,51:64))


#cycles
long_cycles <- cyclesDf |>
  pivot_longer(cols = names(cyclesDf[9:22]),
               names_to = "cycleLet",
               values_to = "cycleNum")
long_cycles$cycleLet <- apply(cbind(long_cycles$cycleLet), 1, 
                                 function(x) substr(x, str_length(x), str_length(x)))
# stiffness
stiffFraction <- stiffnessDf2 |>
  pivot_longer(cols=names(stiffnessDf[9:22]),
               names_to = "cycleLet",
               values_to = "stiffFrac")

stiffFraction$cycleLet <- apply(cbind(stiffFraction$cycleLet), 1, 
                                 function(x) substr(x, str_length(x), str_length(x)))  

long_stiffness <- stiffnessDf |>
  pivot_longer(cols = names(stiffnessDf[9:22]),
               names_to = "cycleLet",
               values_to = "stiffness") 
long_stiffness$cycleLet <- apply(cbind(long_stiffness$cycleLet), 1, 
                                 function(x) substr(x, str_length(x), str_length(x)))
long_stiffness <- long_stiffness |>
  join(stiffFraction,by=names(long_stiffness[1:9]))

# damping
long_damping <- dampingDf |>
  pivot_longer(cols = names(dampingDf[9:22]),
               names_to = "cycleLet",
               values_to = "damping") 
long_damping$cycleLet <- apply(cbind(long_damping$cycleLet), 1, 
                                 function(x) substr(x, str_length(x), str_length(x)))

# nonlinear
long_nonlinear <- nonlinearDf |>
  pivot_longer(cols= names(nonlinearDf[9:22]),
               names_to = "cycleLet",
               values_to = "nonlinear") 
long_nonlinear$cycleLet <- apply(cbind(long_nonlinear$cycleLet), 1, 
                                 function(x) substr(x, str_length(x), str_length(x)))

```

# Merge Everything
```{r}
joined_df <- long_cycles |>
  join(long_stiffness, by=names(long_cycles[1:9]), type = "left") |>
  join(long_damping, by=names(long_cycles[1:9]), type = "left") |>
  join(long_nonlinear, by=names(long_cycles[1:9]), type = "left") 

```

# Add strain rate
```{r}

full_df <- joined_df |>
  mutate(strainRate = 4*amp*freq) 


#reorder so sampleNum is first and get rid of cycleLet
full_df <- full_df[, c(4, 1:3, 5:8, 10:15)]

full_df <- full_df |>
    mutate(stiffness = abs(stiffness)) |>
  select(!chemistry) |>
  drop_na()

```

# Export as csv
```{r}
write.csv(full_df, "clean_helmet.csv", row.names=FALSE)
```


